# Generated by Django 3.2.23 on 2023-12-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coaching_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coaching',
            name='text',
        ),
    ]
