# Generated by Django 3.2.23 on 2023-11-27 12:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name Link'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page_intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Seite'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_extern',
            field=models.CharField(blank=True, max_length=500, verbose_name='Seiten Auswahl'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menu'),
            preserve_default=False,
        ),
    ]
