# Generated by Django 3.2.23 on 2023-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_webpimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
