# Generated by Django 3.2.23 on 2023-11-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_webpimage_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebPImage',
        ),
    ]
