# Generated by Django 3.2.23 on 2023-11-27 10:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0006_homepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='btn_text',
            field=models.CharField(blank=True, max_length=90, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_choice',
            field=models.CharField(blank=True, choices=[('page', 'Verlingung Seite'), ('extern', 'Verlinkung Intern')], max_length=20, verbose_name='Auswahl Verlinkung'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Seiten Link Extern'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Seiten Verlinkung'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skyline',
            field=models.CharField(blank=True, max_length=350, verbose_name='Skyline'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subline',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
