# Generated by Django 3.2.23 on 2023-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20231127_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='link_choice',
            field=models.CharField(blank=True, choices=[('page', 'Verlingung Intern'), ('extern', 'Verlinkung Extern')], max_length=20, verbose_name='Auswahl Verlinkung'),
        ),
    ]
