# Generated by Django 3.2.23 on 2023-11-30 19:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_link_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('headline_text_horizontal_line', wagtail.blocks.StructBlock([('heading', wagtail.blocks.RichTextBlock(blank=True, form_classname='Titel')), ('subline', wagtail.blocks.RichTextBlock(blank=True, form_classname='Subline')), ('paragraph', wagtail.blocks.RichTextBlock(blank=True, form_classname='Text')), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, use_json_field=True),
        ),
    ]
