# Generated by Django 3.2.23 on 2023-12-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_customformsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Kontaktseite'},
        ),
    ]
