# Generated by Django 3.2.23 on 2023-12-08 14:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='legal',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('textfield_full_width', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['h2', 'custom-inline', 'custom-inline-blue'], help_text='Textfeld gesamte Breite, maximal 10.000 Zeichen.', label='Fließtextfeld', max_length=10000, required=True))]))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
