# Generated by Django 3.2.23 on 2023-12-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legal',
            name='text',
        ),
    ]
