# Generated by Django 3.2.23 on 2023-12-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name': 'Fließtextseite'},
        ),
    ]
