# Generated by Django 3.2.23 on 2023-12-07 08:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_remove_legal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='legal',
            name='content',
            field=wagtail.fields.StreamField([('textfield_full_width', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(help_text='Textfeld gesamte breite', label='Fließtextfeld', max_length=5000, required=True))]))], blank=True, use_json_field=True),
        ),
    ]
