# Generated by Django 3.2.23 on 2023-12-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieBannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.TextField(verbose_name='Text des Cookie Banners')),
                ('banner_accept_button_text', models.CharField(default='Cookies akzeptieren', max_length=255, verbose_name='Text des Akzeptieren-Buttons')),
                ('banner_decline_button_text', models.CharField(default='Ablehnen', max_length=255, verbose_name='Text des Ablehnen-Buttons')),
                ('marketing', models.CharField(default='Marketing Code Beschreibung', max_length=255, verbose_name='Marketing')),
                ('javascript_code', models.TextField(blank=True, null=True, verbose_name='JavaScript-Code')),
                ('privacy_policy', models.ForeignKey(blank=True, help_text='Wähle deine Datenschutzseite aus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Datenschutz Seite')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Cookie Banner Einstellungen',
            },
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
