# Generated by Django 3.2.23 on 2023-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='whatsapp',
            field=models.URLField(blank=True, help_text='Whatsapp URL', null=True),
        ),
    ]
