# Generated by Django 3.2.23 on 2023-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0002_alter_socialmediasettings_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysettings',
            options={'verbose_name': 'Einstellungen Button'},
        ),
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'Einstellungen Social Media'},
        ),
        migrations.AddField(
            model_name='mysettings',
            name='book_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='mysettings',
            name='btn_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Seiten Auswahl'),
        ),
    ]
