# Generated by Django 3.2.23 on 2023-11-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0083_workflowcontenttype'),
        ('site_settings', '0003_auto_20231127_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings',
            name='header_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header Logo'),
        ),
        migrations.AlterField(
            model_name='mysettings',
            name='book_appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Seiten Auswahl'),
        ),
        migrations.AlterField(
            model_name='mysettings',
            name='btn_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Button Text'),
        ),
    ]
