# Generated by Django 3.2.23 on 2023-12-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('site_settings', '0004_auto_20231129_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings',
            name='around_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo rund'),
        ),
        migrations.AlterField(
            model_name='mysettings',
            name='header_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='logo quadratisch'),
        ),
    ]
