# Generated by Django 3.2.23 on 2023-12-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_auto_20231205_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Deine WhatsApp-Nummer.', max_length=100, null=True),
        ),
    ]
